"""Regenerate tables from retained results; no hand-entered aggregate scores."""
import json,pathlib,statistics,re
base=pathlib.Path(__file__).resolve().parents[1];out=base/'results'
def read(name):return json.loads((out/name).read_text())
def md(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join(['---']*len(headers))+'|']+['| '+' | '.join(map(str,row))+' |' for row in rows])
def metric(records,method,kind):
 rows=[r for r in records if r['request']['category']==kind];ranks=[]
 for r in rows:
  expected=(r['request']['expected_path'],r['request']['expected_name']);pairs=r.get(method,[])[:8]
  rank=next((i+1 for i,p in enumerate(pairs) if tuple(p)==expected),None);ranks.append(rank)
 return f'{sum(x is not None for x in ranks)}/{len(rows)}',round(sum(1/x if x else 0 for x in ranks)/len(rows),3)
corpora=[];retrieval=[];expanded=[];natural=[];latency=[];ownership=[]
for repo in ['nanus','blogwright','whatsurvey']:
 b=read(repo+'-baseline.json');f=read(repo+'-fixed.json')
 corpora.append([repo,b['files'],b['nodes'],b['edges'],f['nodes'],f['edges']])
 bc=sum(b['edge_counts'].get(k,0) for k in ['calls_resolved','calls_unresolved']);fc=sum(f['edge_counts'].get(k,0) for k in ['calls_resolved','calls_unresolved'])
 ownership.append([repo,bc,b['file_owned_calls'],fc,f['file_owned_calls'],b['edge_counts'].get('calls_resolved',0),f['edge_counts'].get('calls_resolved',0)])
 rows=read(repo+'-retrieval.json');fixed=[q for q in f['queries'] if q['request']['mode']=='explore'][:10]
 fixedhits=sum(q['request']['expected_path'] in [x['node']['path'] for x in q['result'].get('items',[])[:8]] for q in fixed)
 hits=lambda method:sum(bool(r.get(method,{}).get('rank')) for r in rows)
 retrieval.append([repo,f'{hits("baseline")}/10',f'{fixedhits}/10',f'{hits("fts_metadata")}/10',f'{hits("fts_body")}/10',f'{hits("codegraph_raw_fts")}/10' if repo!='nanus' else 'not run',f'{hits("codegraph_query")}/10' if repo!='nanus' else 'not run',f'{hits("codegraph_explore")}/10' if repo!='nanus' else 'not run'])
 for phase in ['baseline','fixed']:
  data=read(repo+'-expanded-'+phase+'.json')
  for kind in ['exact','split']:
   h,m=metric(data,'graph_search',kind);fh,fm=metric(data,'fts_metadata',kind)
   cg=metric(data,'codegraph_raw_fts',kind)[0] if repo!='nanus' else 'not run'
   expanded.append([repo,phase,kind,h,m,fh,fm,cg])
 tasks=read(repo+'-natural.json');row=[repo]
 for method in ['baseline','fixed','fts_metadata','fts_body','codegraph_explore']:
  row.append(f"{sum(r['expected_path'] in r.get(method,[])[:8] for r in tasks)}/5" if method!='codegraph_explore' or repo!='nanus' else 'not run')
 natural.append(row)
 bt=[q['elapsed_us']/1000 for q in b['queries'][:10]];ft=[q['elapsed_us']/1000 for q in f['queries'][:10]]
 latency.append([repo,b['index_ms'],f['index_ms'],round(statistics.median(bt),2),round(statistics.median(ft),2)])
edges=read('application-edges.json');edge_rows=[[e['repo'],e['source']+' → '+e['target'],e['baseline']['found'],e['fixed']['found'],','.join(map(str,e['source_occurrence_lines']))] for e in edges]
text='''# Experiment results

Tables below are generated by `scripts/summarize.py`. Definitions, comparator differences, and threats to validity are in [methodology](01-methodology.md). Full ranked outputs and labels are retained in `results/`.

## Corpus and graph size

'''+md(['Repository','Baseline files','Baseline nodes','Baseline edges','Fixed nodes','Fixed edges'],corpora)+'''

Files include unsupported/text/assets admitted by the graph-search walker. CodeGraph's indexed-file counts refer to a different extraction set; node/edge count superiority is not an accuracy measure.

## Call extraction and ownership

'''+md(['Repository','Baseline calls','Baseline file-owned','Fixed calls','Fixed file-owned','Baseline resolved calls','Fixed resolved calls'],ownership)+'''

The initial JS/TS bug attached all calls to file nodes. Residual file-owned calls include genuine module-level execution and anonymous callbacks without their own extracted callable symbol. The final implementation attributes local initializer calls to the enclosing function. Relationship deduplication can reduce edge counts when previously distinct variable-owned calls acquire the same correct function owner. More/fewer resolved edges alone cannot establish precision or recall.

## Discovery: labelled-file hits

'''+md(['Repository','Baseline @8','Fixed @8','FTS metadata @8','FTS body @8','CodeGraph raw FTS @8','CodeGraph query @8','CodeGraph explore files'],retrieval)+'''

This is the small discovery set, not the principal generalization test. CodeGraph explore uses its own file budget and context assembly, rather than eight graph-search symbol slots. The FTS body arm did not improve the discovery hit count beyond metadata; that does not show bodies are unnecessary for broader task language.

## Expanded: labelled-symbol hits and reciprocal ranks

'''+md(['Repository','Engine phase','Query','Graph Hit@8','Graph MRR@8','FTS Hit@8','FTS MRR@8','CodeGraph raw FTS Hit@8'],expanded)+'''

Across the baseline, exact names succeed for 90/90 targets; split identifiers succeed for 32/90. Identifier-aware FTS over the same baseline candidates finds 89/90 split targets. The repeated FTS rows for the fixed phase use fixed extraction metadata; production graph-search still uses its multi-term heuristic. This is an identifier-derived benchmark, not a semantic question-answering score. Full CodeGraph explore was not run on these 180 prompts.

## Task-language challenge: labelled-file hits

'''+md(['Repository','Baseline @8','Fixed @8','FTS metadata @8','FTS body @8','CodeGraph explore files'],natural)+'''

The challenge deliberately changes vocabulary. Its much lower results are the strongest warning against generalizing the identifier test. More bodies help some questions but do not solve synonym handling, candidate coverage, or ranking. CodeGraph also misses intended files. Alternative relevant files are not exhaustively graded, so these are diagnostic labelled-file hits, not full-answer correctness scores.

## Eight source-confirmed application call relationships

'''+md(['Repository','Relationship','Baseline','Fixed','Source line(s)'],edge_rows)+'''

These cases check actual source calls, with hashes and endpoints in `results/application-edges.json`. The first attempted label incorrectly assumed `syncDocuments` called `listPublishablePosts`; source inspection showed that the actual caller is `syncPds`, and the label was corrected before scoring. This check also uncovered the local-initializer ownership defect. The sample is too small and deliberately targeted to estimate whole-graph precision/recall.

## Timing observations, not a backend race

'''+md(['Repository','Baseline index ms','Fixed index ms','Baseline discovery median ms','Fixed discovery median ms'],latency)+'''

These are debug-build, single-run observations. The initial exploratory baseline included overlapping runs; the complete reproduction script runs repository indexing sequentially. Query times cover resident QueryEngine work and source/snippet reads, not the full SearchService freshness scan or CLI startup. FTS lookup timings in retained retrieval JSON exclude index construction and graph/context assembly. Do not compare those as end-to-end speedups. A first conservative binding implementation scanned all symbols per reference and caused a large indexing slowdown; the final version retains multiplicity in name indexes instead. That temporary implementation was not retained.

## Rejected and deferred experiments

- Broad punctuation/stop-word normalization exposed a task-language regression: normalizing `server?` to `server` flooded results with server symbols and displaced the intended publication-record file. The final fix normalizes only single symbol-shaped queries, preserving multi-term ranking until it can be replaced systematically.
- Body indexing was tested as a separate FTS field rather than assumed necessary. It helps some task-language questions but has a larger indexing/refresh footprint.
- An exact-name lane should accompany BM25. Pure split-token BM25 misses one exact expanded target despite baseline exact lookup being perfect.
- No embedding, reranker, compiler index, Grafeo-to-SQLite migration, or end-to-end LLM-agent experiment was run. Those remain proposals with explicit gates in the improvement plan.
'''
(base/'03-experiments.md').write_text(text)
summary={'corpora':corpora,'discovery':retrieval,'expanded':expanded,'natural':natural,'ownership':ownership,'latency':latency,'application_edges':{'baseline':sum(e['baseline']['found'] for e in edges),'fixed':sum(e['fixed']['found'] for e in edges),'total':len(edges)}}
(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
print(json.dumps(summary,indent=2))
